# Generated by Django 5.1.2 on 2024-10-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_search_searchp_rename_user_userp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchP',
            new_name='Search',
        ),
        migrations.RenameModel(
            old_name='UserP',
            new_name='User',
        ),
    ]
