# Generated by Django 5.1.2 on 2024-10-17 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_email_profile_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='descript',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
