# Generated by Django 5.1.2 on 2024-10-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_profile_descript_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
