# Generated by Django 5.1.2 on 2024-10-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
